### ISSUE TITLE
NullPointerException in Gradle plugin when using key from ssh-keygen

### ISSUE THREAD

**Issue by nickavv** [StarChart-Labs/lockdown#26]
I used `ssh-keygen -t rsa` to create a key pair called lockdown_rsa.
I defined a gradle task as such:

```
task addPgCredentials(type: com.coronaide.lockdown.gradle.task.AddCredentialsTask){
    publicKey "${rootDir}/lockdown_rsa.pub"
    credentialFile "${projectDir}/src/main/resources/credentials-dev.properties"
}
```

lockdown_rsa.pub is present in ${rootDir}. When running my task: `./gradlew :repository.pg:addPgCredentials -PlookupKey=key --stacktrace` I see the following stack trace:

```
* What went wrong:
Execution failed for task ':repository.pg:addPgCredentials'.
> java.lang.NullPointerException (no error message)

...cutting out the boring part of the stack trace....
Caused by: java.lang.NullPointerException
        at com.coronaide.lockdown.CredentialStore.readAndDecodeKey(CredentialStore.java:341)
        at com.coronaide.lockdown.CredentialStore.addOrUpdateCredentials(CredentialStore.java:87)
        at com.coronaide.lockdown.CredentialStore$addOrUpdateCredentials$0.call(Unknown Source)
        at com.coronaide.lockdown.gradle.task.AddCredentialsTask.exec(AddCredentialsTask.groovy:52)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:133)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:126)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:115)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more
```

**Comment by romeara** [comment]
2 Questions:
- What format of RSA key is generated by that command? Is is PEM?
- If not PEM, if you generate a PEM-format key, does that work?

**Comment by nickavv** [comment]
Apparently ssh-keygen does not generate PEM by default. From the manpage:

> Specify a key format for the -i (import) or -e (export) conversion options. The supported key formats are: “RFC4716” (RFC 4716/SSH2 public or private key), “PKCS8” (PEM PKCS8 public key) or “PEM” (PEM public key). The default conversion format is “RFC4716”.

So to get a PEM key I'd need to run
`ssh-keygen -t rsa -m PEM`

I will try and let you know

**Comment by nickavv** [comment]
The answer is no that did not help, I get the same exact exception trace

**Comment by romeara** [comment]
What about PKCS8 (PEM PKCS8 public key)?

**Comment by romeara** [comment]
Based on this:
http://www.cryptosys.net/pki/rsakeyformats.html

I believe lockdown currently supports PKCS#1

**Comment by romeara** [comment]
Or PKCS8. In either case, the start and end blocks appear incorrect

**Comment by romeara** [comment]
@nickavv Can you attach example keys to this ticket

**Comment by nickavv** [comment]
lockdown_rsa{.pub} were the original keys I generated that I first saw this problem with.
pem_rsa{.pub} were the ones I generated in my last comment to test the `-m PEM` flag
[keys.zip](https://github.com/Corona-IDE/lockdown/files/1056717/keys.zip)

**Comment by romeara** [comment]
Self note: Keys generated have a getFormat() method, which could map to the correct header as specified [here](https://tls.mbed.org/kb/cryptography/asn1-key-structures-in-der-and-pem). 

Headers could then be used to determine the correct encoding - CredentialStore currently only accepts PKCS1

**Comment by romeara** [comment]
So bouncycastle only supports the PKCS1 encoding at all - I'll make the error more clear, but unfortunately can't expand support at this time
